---
abstract: 'Danish CVR (VAT Registration) code generator/validator'
author:
  - 'Jonas B. Nielsen, (jonasbn) <jonasbn@cpan.org>'
build_requires:
  Data::FormValidator: '0'
  Taint::Runtime: '0'
  Test::Exception: '0'
  Test::Kwalitee: '0'
  Test::More: '0'
  Test::Perl::Critic: '0'
  Test::Prereq::Build: '0'
  Test::Taint: '0'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.142060'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Business-DK-CVR
provides:
  Business::DK::CVR:
    file: lib/Business/DK/CVR.pm
    version: '0.09'
  Class::Business::DK::CVR:
    file: lib/Class/Business/DK/CVR.pm
    version: '0.09'
  Data::FormValidator::Constraints::Business::DK::CVR:
    file: lib/Data/FormValidator/Constraints/Business/DK/CVR.pm
    version: '0.09'
requires:
  Carp: '0'
  Class::InsideOut: '0'
  English: '0'
  Exporter: '0'
  Params::Validate: '0'
  Readonly: '0'
  Scalar::Util: '0'
  perl: '5.008'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Business-DK-CVR
  homepage: http://logicLAB.jira.com/browse/BDKCVR
  license: http://www.perlfoundation.org/artistic_license_1_0
  projectChangelog: http://logiclab.jira.com/browse/BDKCVR#selectedTab=com.atlassian.jira.plugin.system.project%3Achangelog-panel
  projectSite: http://logicLAB.jira.com/browse/BDKCVR
  projectWiki: http://logiclab.jira.com/wiki/display/BDKCVR/Home
  repository: https://github.com/jonasbn/bdkcvr
version: '0.09'
