---
name: Business-DK-CVR
version: 0.05
author:
  - 'Jonas B. Nielsen, (jonasbn) <jonasbn@cpan.org>'
abstract: Danish CVR (VAT Registration) code generator/validator
license: artistic
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Business-DK-CVR
  homepage: http://logicLAB.jira.com/browse/BDKCVR
  license: http://www.perlfoundation.org/artistic_license_1_0
  repository: http://logicLAB.jira.com/svn/BDKCVR
build_requires:
  Data::FormValidator: 0
  Taint::Runtime: 0
  Test::Exception: 0
  Test::Kwalitee: 0
  Test::More: 0
  Test::Perl::Critic: 0
  Test::Prereq::Build: 0
  Test::Taint: 0
requires:
  Business::DK::PO: 0.02
  Carp: 0
  Class::InsideOut: 0
  English: 0
  Exporter: 0
  Scalar::Util: 0
configure_requires:
  Module::Build: 0.35
provides:
  Business::DK::CVR:
    file: lib/Business/DK/CVR.pm
    version: 0.05
  Class::Business::DK::CVR:
    file: lib/Class/Business/DK/CVR.pm
    version: 0.01
  Data::FormValidator::Constraints::Business::DK::CVR:
    file: lib/Data/FormValidator/Constraints/Business/DK/CVR.pm
    version: 0.01
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
