--- #YAML:1.0
name: Business-DK-CVR
version: 0.02
author:
  - Jonas B. Nielsen, (jonasbn) <jonasbn@cpan.org>
abstract: a danish CVR (VAT Registration) code generator/validator
license: artistic
generated_by: Module::Build version 0.2611, without YAML.pm
